/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppChart {
    }
    interface AppChild {
        "p1": string;
        "p2": string;
    }
    interface AppHome {
    }
    interface AppNest {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppStore {
    }
    interface AppTodo {
    }
    interface CheckTodo {
        "done": boolean;
        "n": number;
        "text": string;
    }
}
declare global {
    interface HTMLAppChartElement extends Components.AppChart, HTMLStencilElement {
    }
    var HTMLAppChartElement: {
        prototype: HTMLAppChartElement;
        new (): HTMLAppChartElement;
    };
    interface HTMLAppChildElement extends Components.AppChild, HTMLStencilElement {
    }
    var HTMLAppChildElement: {
        prototype: HTMLAppChildElement;
        new (): HTMLAppChildElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNestElement extends Components.AppNest, HTMLStencilElement {
    }
    var HTMLAppNestElement: {
        prototype: HTMLAppNestElement;
        new (): HTMLAppNestElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppStoreElement extends Components.AppStore, HTMLStencilElement {
    }
    var HTMLAppStoreElement: {
        prototype: HTMLAppStoreElement;
        new (): HTMLAppStoreElement;
    };
    interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {
    }
    var HTMLAppTodoElement: {
        prototype: HTMLAppTodoElement;
        new (): HTMLAppTodoElement;
    };
    interface HTMLCheckTodoElement extends Components.CheckTodo, HTMLStencilElement {
    }
    var HTMLCheckTodoElement: {
        prototype: HTMLCheckTodoElement;
        new (): HTMLCheckTodoElement;
    };
    interface HTMLElementTagNameMap {
        "app-chart": HTMLAppChartElement;
        "app-child": HTMLAppChildElement;
        "app-home": HTMLAppHomeElement;
        "app-nest": HTMLAppNestElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-store": HTMLAppStoreElement;
        "app-todo": HTMLAppTodoElement;
        "check-todo": HTMLCheckTodoElement;
    }
}
declare namespace LocalJSX {
    interface AppChart {
    }
    interface AppChild {
        "p1"?: string;
        "p2"?: string;
    }
    interface AppHome {
    }
    interface AppNest {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppStore {
    }
    interface AppTodo {
    }
    interface CheckTodo {
        "done": boolean;
        "n": number;
        "text": string;
    }
    interface IntrinsicElements {
        "app-chart": AppChart;
        "app-child": AppChild;
        "app-home": AppHome;
        "app-nest": AppNest;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-store": AppStore;
        "app-todo": AppTodo;
        "check-todo": CheckTodo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-chart": LocalJSX.AppChart & JSXBase.HTMLAttributes<HTMLAppChartElement>;
            "app-child": LocalJSX.AppChild & JSXBase.HTMLAttributes<HTMLAppChildElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-nest": LocalJSX.AppNest & JSXBase.HTMLAttributes<HTMLAppNestElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-store": LocalJSX.AppStore & JSXBase.HTMLAttributes<HTMLAppStoreElement>;
            "app-todo": LocalJSX.AppTodo & JSXBase.HTMLAttributes<HTMLAppTodoElement>;
            "check-todo": LocalJSX.CheckTodo & JSXBase.HTMLAttributes<HTMLCheckTodoElement>;
        }
    }
}
